production:
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  adapter: postgresql
  database: shibe_rails
  host: <%= ENV.fetch('PGHOST', 'localhost') %>
  username: <%= ENV['PGUSER'] %>
